# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require_relative 'TimedPut'

def fibonacci_hash
  Hash.new{ |h,k| h[k] = k < 2 ? k : h[k-1] + h[k-2] }
end

def fib_evens(number)
 fibonacci_hash.select { |key, val| (val < number && val % 2 == 0) ? val : 0 }.values.reduce(:+)
end

def dumb_fib(number)
  a = {}
  (2..33).each do |val|
     a[val] = fibonacci_hash[val] < number && fibonacci_hash[val] % 2 == 0 ? fibonacci_hash[val] : 0
  end
  a.values.reduce(:+)
end

tputs{dumb_fib 4000000}