# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require_relative 'TimedPut'

def fibonacci_hash
  Hash.new{ |h,k| h[k] = k < 2 ? k : h[k-1] + h[k-2] }.merge(0 => 0, 1 => 1)
end

def fib_evens(number)
 fibonacci_hash.select { |key, val| val < number}.values.reduce(:+)
end

tputs{fib_evens 4000000}